server:
  port: 8000 # 设置应用运行的端口号

# 其他自定义配置项
app:
  name: Smart Scheduler Backend
  version: 1.0.0

# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://115.29.241.234:3306/HarmonyOS_DB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://115.29.241.234:3306/Database_experiments?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "@84986730Pkl"
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB      # 单个文件最大大小
      max-request-size: 100MB  # 单次请求所有文件总大小

  mail:
    host: smtp.qq.com
    port: 465
    username: 3465154309@qq.com
    password: bzcrbemqjuqacjab
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
        timeout: 5000
        connectiontimeout: 5000
        writetimeout: 5000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: org.example.smart_schedulerbackend.model.entity



sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: 0s5Y8tKf6RzLmJnQv2xW9cA1bB3dC4eD5gE6hF7iG8jH9kI=
    user-ttl: 7200000
    user-token-name: token

  #Redis相关配置
redis:
  host: localhost
  port: 6379
  database: 0 #操作的是0号数据库(redis存在0-15号数据库（默认），在命令中使用select来切换)
  jedis:
    #Redis连接池配置
    pool:
      max-active: 8 #最大连接数
      max-wait: 1ms #连接池最大阻塞等待时间
      max-idle: 4 #连接池中的最大空闲连接
      min-idle: 0 #连接池中的最小空闲连接
aliyun:
  oss:
    endpoint: https://oss-cn-guangzhou.aliyuncs.com
    bucketName: web-carbon

# 自定义验证码配置
verification:
  code-length: 6
  expire-seconds: 300
  email-subject: "【验证码】你的验证码"